### ISSUE TITLE
Nice thing

### ISSUE THREAD

**Issue by abdoei** [Luvkush8941/DSA-Using-Cplusplus#1]
On using Colab AI for testing it for the first time, it cited your work here!
![image](https://github.com/Luvkush8941/DSA-Using-Cplusplus/assets/64744285/0b0255d2-0bc1-4d7c-9396-f0931403c9d0)
I thought it would make you happy for a moment :smile:

**Comment by Luvkush8941** [comment]
Nice , to see that i had contributed something to the community 😀
